# + -------------------------------------------------------------------------------- + #
# | GRIEF SETTINGS ( 매크로 방지 설정 )
# + -------------------------------------------------------------------------------- + #
griefMacro:
  # 해당 시간동안 블럭을 캐거나 낚시를 하지 않으면 스택을 초기화 ( 초 )
  resetTimer: 120
  # 해당 숫자만큼 스택이 쌓이면 매크로 여부를 확인
  checkMacroStack: 100
  # 매크로 확인 메시지 응답 제한시간 ( 초 )
  responseTimeOut: 60

  # 매크로 감지 메시지 전송 시 재생할 소리
  # 형식 : 소리이름/높낮이
  # 소리 목록 : https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  # ( 제일 앞에 '#' 을 붙여 주석으로 처리하시면 소리가 나지 않습니다 )
  sound: "ENTITY_EXPERIENCE_ORB_PICKUP/2"

# + -------------------------------------------------------------------------------- + #
# | MESSAGE, ERRORMESSAGE SETTINGS ( 메시지 설정 )
# | 유저에게 출력되지 않을 메세지는 해당 라인을 지우시거나
# | 해당 라인의 제일 앞에 '#' 을 붙여 주석으로 처리하시면 됩니다.
# + -------------------------------------------------------------------------------- + #
messages:
  # 접두사
  prefix: " &6매크로 방지 | "
  # 매크로 확인 시 유저에게 뜰 메시지
  macroMessage: "&a&l채팅에 숫자 %number%를 입력해주세요!"
  # /매크로 확인 명령어 사용 시 뜰 메시지
  macroCommand: "&a성공적으로 매크로 확인 메시지를 전송했습니다!"
  # 리로드 시 메시지
  reloadCompleted: "&a리로드가 완료되었습니다."
  # 매크로 사용으로 추방 시 메시지
  kickMessage: "&c매크로 사용으로 추방당했습니다."
  # 매크로가 아님을 확인하였을 때
  verifiedMessage: "&a인증이 완료되었습니다!"
  # 도움말
  helpMessage:
    - "&6=== 도움말 ==="
    - "&6/매크로 리로드 - 플러그인을 리로드합니다"
    - "&6/매크로 확인 [<유저네임>] - 해당 플레이어에게 매크로 확인 메시지를 전송합니다."

errorMessages:
  # 권한이 부족할 시
  permissionDenied: "&c권한이 부족합니다."
  # 서버에 없는 플레이어에게 매크로 확인 메시지를 보내려 할 때
  noExistPlayer: "&c존재하지 않는 플레이어입니다."
  # 매크로 확인 시 인증코드를 틀렸을 때
  wrongCode: "&c코드가 일치하지 않습니다."
