name: ST-AntiMacro # TODO: 수정
main: net.starly.antimacro.AntiMacroMain # TODO: 수정
author: Starly Team
website: http://starly.kr/

description: AntiMacro Plugin. # TODO: 수정

softdepend:
  - ST-Core

version: 1.0
api-version: 1.13

permissions:
  starly.antimacro.*:
    description: wildcard permission
    children:
      - starly.antimacro.reload
      - starly.antimacro.check
      - starly.antimacro.bypass
  starly.antimacro.reload:
    description: reload permission
    default: op
  starly.antimacro.check:
    description: check permission
    default: op
  starly.antimacro.bypass:
    description: bypass permission
    default: op

commands:
  매크로:
    description: Macro Command